insert into t_suburb_deliver_fee(suburb, deliverFee) values('Algester', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Annerley', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Acacia Ridge', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Auchenflower', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Ascot', 18.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Archerfield', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Browns Plains', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Bowen Hills', 14.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Bridgeman Downs', 22.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Bardon', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Bulimba', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Coopers Plains', 3.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Calamvale', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Carindale', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Carina', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('City', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Coorparoo', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Camp Hill', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Cannon Hill', 12.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Chermside', 18.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Chermside West', 18.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Carseldine', 22.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Drewvale', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Doolandella', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Daisy Hill', 14.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Eight Mile Plains', 5.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('East Brisbane', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Fortitude Vally', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Forest Lake', 12.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Greenslopes', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Herston', 12.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Highgate Hill', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Hamilton', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Holland Park', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Holland Park West', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Hawthorne', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Indooroopilly', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Jimbooba', 16.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Jindalee', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Lutwyche', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Kuraby', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Kelvin Grove', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Kangaroo Point', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Macgregor', 4.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Mt Gravatt', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Moorooka', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Mt Gravatt East', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Morningside', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Milton', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Mansfield', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Mitchelton', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Norman Park', 15.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Newmarket', 13.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Nundah', 20.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('New Farm', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Oxley', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Parkinson', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Paddington', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Robertson', 3.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Runcorn', 5.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Rochedale', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Rochedale South', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Rocklea', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Red Hill', 12.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Salisbury', 3.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Sunnybank', 4.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Sunnybank Hills', 5.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Streetton', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('St Lucia', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('South Bank', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('South Brisbane', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Spring Hill', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Stafford', 18.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Slacks Creek', 12.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Taringa', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Toowong', 10.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Tarragindi', 7.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Teneriffe', 11.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Underwood', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Upper Mt Gravatt', 4.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Virginia', 20.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Windsor', 13.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Woolongabba', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Wishart', 6.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('West End', 9.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Woodridge', 8.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Wooloowin', 20.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Wavell Heights', 18.00);
insert into t_suburb_deliver_fee(suburb, deliverFee) values('Yeronga', 9.00);
